### ISSUE TITLE
RA VSCode settings changed?

### ISSUE THREAD

**Issue by melMass** [ericseppanen/cargo-cranky#13]
Hey,

Thanks for this crate, very useful.
I might be doing something wrong but from the README, I guessed the settings name changed to `rust-analyzer.check.command` but setting it like so:

```json
{
 "rust-analyzer.check.command": "cranky",
}
```

Was not working, no errors but I wasn't getting inline warnings and errors from cranky.

The following did:

```json
  "rust-analyzer.check.overrideCommand": [
        "cargo",
        "cranky",
        "--workspace",
        "--message-format=json",
        "--all-targets"
    ]
 ```

**Comment by ericseppanen** [comment]
You're right. The vscode GUI still works the same as before, but it's storing a different setting now:
```txt
{
    "rust-analyzer.check.command": "cranky"
}
```

**Comment by ericseppanen** [comment]
Updated the README in 1bc1d2b27e8cb9eb75.

Thanks for pointing this out!
